# Generated by Django 3.2.9 on 2021-12-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rental_id', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('value', models.IntegerField()),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Account Transfer', 'Account Transfer')], max_length=16)),
                ('type', models.CharField(blank=True, choices=[('Car Rent', 'Car Rent'), ('Expenditure', 'Expenditure'), ('PCO', 'PCO'), ('Service & Repairs', 'Service & Repairs'), ('Other Income', 'Other Income'), ('Car Sold', 'Car Sold')], max_length=17)),
                ('in_out', models.CharField(blank=True, choices=[('Income', 'Income'), ('Outcome', 'Outcome')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='deletes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('postcode', models.CharField(blank=True, max_length=50)),
                ('license_number', models.IntegerField(blank=True)),
                ('LN_expiration_date', models.DateField(blank=True, max_length=100)),
                ('NI', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=8)),
                ('notes', models.CharField(blank=True, max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='driverDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=20)),
                ('doc', models.FileField(upload_to='driverDocs/')),
            ],
        ),
        migrations.CreateModel(
            name='lastSigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='owner_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start', models.DateField(max_length=100)),
                ('end', models.DateField(max_length=100)),
                ('amount_due', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('balance', models.CharField(max_length=99999)),
            ],
        ),
        migrations.CreateModel(
            name='owner_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ownerDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_account_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=20)),
                ('doc', models.FileField(upload_to='ownerDocs/')),
            ],
        ),
        migrations.CreateModel(
            name='permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=300)),
                ('level1', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('level2', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('level3', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('level4', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField()),
                ('driver_full_name', models.CharField(max_length=200)),
                ('vehicle_id', models.IntegerField()),
                ('vehicle_plate', models.CharField(max_length=20)),
                ('hire_date', models.DateField(max_length=100)),
                ('return_date', models.DateField(max_length=100)),
                ('balance', models.CharField(max_length=99999)),
                ('deposit', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='rentalDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=20)),
                ('doc', models.FileField(upload_to='rentalDocs/')),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20)),
                ('registered_company_name', models.CharField(blank=True, max_length=100)),
                ('owner_name', models.CharField(blank=True, max_length=100)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('cylinder_capacity', models.CharField(blank=True, max_length=100)),
                ('fuel_type', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True)),
                ('mileage', models.IntegerField(blank=True)),
                ('LOGBOOK_first_date_of_registration', models.DateField(blank=True, max_length=100)),
                ('mot_expiration_date', models.DateField(blank=True, max_length=100)),
                ('pco_expiration_date', models.DateField(blank=True, max_length=100)),
                ('road_tax_expiration_date', models.DateField(blank=True, max_length=100)),
                ('value', models.IntegerField(blank=True)),
                ('rent', models.IntegerField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('On Rent', 'On Rent'), ('Available', 'Available for rent'), ('Sold', 'Sold'), ('Scrapped', 'Scrapped'), ('Damaged', 'Damaged')], max_length=9)),
                ('notes', models.CharField(blank=True, max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='vehicleDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=20)),
                ('doc', models.FileField(upload_to='vehicleDocs/')),
            ],
        ),
    ]
