# Generated by Django 3.2.9 on 2021-12-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_rename_owner_account_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
