# Generated by Django 3.2.9 on 2021-12-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_account_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
