# Generated by Django 3.2.9 on 2021-12-31 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0007_permissions_level5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='level5',
        ),
    ]
